import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Control App",
  description:
    "Generated by Abanob Shenoda with help from God Jesus and St. Abader and Ereny His Sister",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
